---
abstract: 'Examples in Perl 6'
author:
  - 'Gabor Szabo <szabgab@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl6-Cookbook
no_index:
  directory:
    - t
    - xt
    - share
    - inc
requires:
  File::ShareDir: 1.00
  perl: 5.008000
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn1.hostlocal.com/szabgab/trunk/Perl6-Cookbook
version: 0.04
